### ISSUE TITLE
Freezes

### ISSUE THREAD

**Issue by Wiilf** [ceejeeb/SpeedTest#1]
No  matter what is done, this simply freezes. I cant figure it out. It got a full GUI and adds the found servers into ListView, any idea why it freezes right from master ? 

VS2019, .NET Core 1.0 - 3.1 (all same issue)

**Comment by ceejeeb** [comment]
I have just pushed an update. Nothing specific other than simple upgrades. I ran it no problem. Let me know how you get on.

**Comment by Wiilf** [comment]
Same result on Release

Unhandled exception. System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at SpeedTest.SpeedTestClient.TestDownloadSpeed(Int32 retryCount, Server server) in SpeedTestClient.cs:line 106
   at SpeedTest.ClientApp.Program.Main() in Program.cs:line 15

**Comment by ceejeeb** [comment]
Where are you based? It defaults to look for servers in the United Kingdom. You can change this in the settings file.

**Comment by Wiilf** [comment]
I wrote a winforms GUI for this, my country is correct and sponsors come into listview control, really nice app. But the part that fails is testing download/upload

**Comment by ceejeeb** [comment]
the stack trace points to no servers in the ordered list. Are you sure the server lookup is returning servers in the country you have specified in the settings file?https://github.com/ceejeeb/SpeedTest/blob/67f9094e4f159b308d516fa11c0ca73147dd7f62/SpeedTest/Models/Settings.cs#L31
Check the country attribute on the elements returned from this url: http://c.speedtest.net/speedtest-servers-static.php

**Comment by Wiilf** [comment]
Oh thank you, I will check that! It looks like I may of missed that. 

If your interested in the full GUI project files I'll send you the zip
